### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Tong-Hao741** [LinghaoChan/HumanMAC#10]
作者您好，请问./data/data_multi_modal  下的data_candi_t_his25_t_pred100_skiprate20.npz & t_his25_1_thre0.500_t_pred100_thre0.100_filtered_dlow.npz  应该去哪里下载呢？

**Comment by LinghaoChan** [comment]
@Tong-Hao741 Thanks for your interest. 

Please read the [data preparation](https://github.com/LinghaoChan/HumanMAC?tab=readme-ov-file#data) part carefully. We said that:
> We adopt the data preprocessing from [GSPS](https://github.com/wei-mao-2019/gsps), which you can refer to [here](https://drive.google.com/drive/folders/1sb1n9l0Na5EqtapDVShOJJ-v6o-GZrIJ) and download all files into the `./data` directory. 

---
翻译 (Translation)

如果您不擅长阅读英语，请参照中文文档中[数据准备](https://github.com/LinghaoChan/HumanMAC/tree/main/doc-CN#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87)部分的说明：
> 我们继承了[GSPS](https://github.com/wei-mao-2019/gsps)的数据预处理框架和数据集。可以从[此处](https://drive.google.com/drive/folders/1sb1n9l0Na5EqtapDVShOJJ-v6o-GZrIJ)下载数据集文件，并把所有文件放在`./data`目录下。

**Comment by Tong-Hao741** [comment]
十分感谢，已经下好了

**Comment by LinghaoChan** [comment]
It seems that the issue has been resolved. I will close it.
