### ISSUE TITLE
Not SOTA?

### ISSUE THREAD

**Issue by hihiok** [LinghaoChan/HumanMAC#12]

**Comment by hihiok** [comment]
Diverse Human Motion Prediction Guided by Multi-Level Spatial-Temporal Anchors
(ECCV2022 oral) has better performance actually.

**Comment by LinghaoChan** [comment]
We do NOT claim our method is a SOTA method, but a simple yet effective method. We do NOT care whether it is SOTA or not, but it is easy to train or use. Actually, HumanMAC has also been used in some recent research ([Interactive Humanoid](https://arxiv.org/pdf/2312.08983.pdf)), indicating it is easy to use. We also find that a co-current ICCV23 work BeLFusion also did not compare your mentioned work. I think the existing benchmark is not large enough to fairly evaluate recent work. 

I like to name these performances as "COMPARABLE" but not "SOTA". "Simple yet effective" is what we like.

**Comment by hihiok** [comment]
But you have claimed in your paper "As can be seen, for Human3.6M, our method achieves state-of-the-art results on both ADE and FDE metrics". Also, you claimed " Bolded numbers denote the state-of-the-art results."  and bolded some of your results.

**Comment by LinghaoChan** [comment]
The statement is applicable to the compared baselines in the paper. We take the BeLFusion's baselines as our baselines. Our works are both peer-reviewed, which indicates our work is acknowledged by the community. The metric cannot reflect everything.

**Comment by hihiok** [comment]
Thanks for your prompt response. Any reasons why not take that paper as a baseline since it's working on the same task?

**Comment by LinghaoChan** [comment]
> Thanks for your prompt response. Any reasons why not take that paper as a baseline since it's working on the same task?

The author of that work and I know each other. The arxiv version of it seems not public when submitting or getting accepted by ECCV. Therefore, the community seems not to know much about the information about it in time. Therefore, some late works did not compare with it. And I followed these (late) works. After HumanMAC getting accepted, Sirui told me that. And I cite it accordingly. 

BTW, the SOTA is really not really essential. An easy-to-train/use method is the wise choice for some downstream tasks and the application.

**Comment by LinghaoChan** [comment]
Seems no further question. I close it.
