### ISSUE TITLE
human motion completion data

### ISSUE THREAD

**Issue by nnynngn** [LinghaoChan/HumanMAC#13]
Hello Linghao, is the quality of the samples added through switch high enough to be used as a means of data expansion? Can the prediction accuracy be improved if the samples generated during the switch process are put into the training set?
Thank you for you attention.
Best wishes.

**Comment by LinghaoChan** [comment]
@nnynngn Thanks for your interest. 

Interesting idea. I think it is a promising way to have a try. Maybe the ideal result is better diversity, due to more composition of the motion data. However, you might lose the accuracy because of the expansion. As I am not very concerned about the SOTA on the tables, I think it might be a wise choice to have a try.

**Comment by nnynngn** [comment]
@LinghaoChan  Thank you for your reply.
Is the diversity of motion beneficial in the field of autonomous driving and robot collaboration? Previous research seemed to focus on accuracy, and I didn’t quite understand the benefits of diversity. can you explain it please. Thanks a lot.

**Comment by LinghaoChan** [comment]
> @LinghaoChan Thank you for your reply. Is the diversity of motion beneficial in the field of autonomous driving and robot collaboration? Previous research seemed to focus on accuracy, and I didn’t quite understand the benefits of diversity. can you explain it please. Thanks a lot.

Definitely beneficial!

I take a naive example. If a motion dataset comes up with 2 subsets (A, and B). The A subset is with motion data like walking and B subset is with motion data like sitting. If a diffusion model learns the continuity of the whole sequence, you can use the switch ability of HumanMAC to produce some novel motions, like walking and then sitting. These novel motions can resolve the limited data access problem to some extend.

**Comment by nnynngn** [comment]
Thanks a lot.

**Comment by LinghaoChan** [comment]
welcome
