### ISSUE TITLE
Why not add positional encoding to motion seq.

### ISSUE THREAD

**Issue by Yuanhong-Zheng** [LinghaoChan/HumanMAC#14]
Hello! Your work is awesome and worth learning from. Why not add positional encoding to the input motion sequence (in modulation part) and y_t (motion with noise from sampling or diffusion process)? How do the model recognize the frame order in a motion seq without them?

**Comment by Yuanhong-Zheng** [comment]
> Hello! Your work is awesome and worth learning from. Why not add positional encoding to the input motion sequence (in modulation part) and y_t (motion with noise from sampling or diffusion process)? How do the model recognize the frame order in a motion seq without them?

Is the sequence_embedding in the code has the same function as PE?

**Comment by LinghaoChan** [comment]
> > Hello! Your work is awesome and worth learning from. Why not add positional encoding to the input motion sequence (in modulation part) and y_t (motion with noise from sampling or diffusion process)? How do the model recognize the frame order in a motion seq without them?
> 
> Is the sequence_embedding in the code has the same function as PE?

exactly the learnable embeddings.

**Comment by Yuanhong-Zheng** [comment]
> > > Hello! Your work is awesome and worth learning from. Why not add positional encoding to the input motion sequence (in modulation part) and y_t (motion with noise from sampling or diffusion process)? How do the model recognize the frame order in a motion seq without them?
> > 
> > 
> > Is the sequence_embedding in the code has the same function as PE?
> 
> exactly the learnable embeddings.

Got it, thanks!
