### ISSUE TITLE
为什么hip的位置固定

### ISSUE THREAD

**Issue by koukau77** [LinghaoChan/HumanMAC#15]
谢谢你的工作。我在可视化结果中发现模型的hip的位置是不会变化的，对于人体运动来说，这不自然。
可以问下原因吗

**Comment by LinghaoChan** [comment]
@koukau77 Thanks for your question. 

As the dataset and benchmark use this setting, we follow such a setting. I think it is ok if your dataset includes global trajectories.

**Comment by koukau77** [comment]
Thank you!
