### ISSUE TITLE
用自己的数据实现

### ISSUE THREAD

**Issue by xiaomadegit** [LinghaoChan/HumanMAC#16]
您好，感谢您的工作，我想请问一下如何用自己的数据进行训练，我的数据是只有一个人物的多种动作视频mp4,我看到您的数据遵循gpsp,而gpsp遵循VideoPose3D,我现在将所有mp4视频数据按照VideoPose3D的一个视频野外推理功能部分的数据处理步骤https://github.com/facebookresearch/VideoPose3D/blob/main/INFERENCE.md，进行了处理，得到了一个coco格式的二维动作数据的.npz文件，然后得到了一个应该符合human3.6m格式.npz的三维的姿态数据文件，现在我想用这样的自己的数据进行您的工作，这样可行吗，如果可行，我应该怎么修改您的各种文件，能够正常训练和推理评估呢。
还有data_multi_modal
│   ├── data_candi_t_his25_t_pred100_skiprate20.npz
│   └── t_his25_1_thre0.500_t_pred100_thre0.100_filtered_dlow.npz这部分的文件是什么意思呢，我现在只有前面所说的两个姿态文件，怎么才能正常训练呢，非常感谢

**Comment by LinghaoChan** [comment]
按照你的说法，按理是应该可行的。你说的这些文件其他issue我记得有提过，你可以看一下。这是测diversity指标的，倒也没那么重要。

**Comment by xiaomadegit** [comment]
谢谢回复，所以这两个文件没有是不是不影响训练模型data_candi_t_his25_t_pred100_skiprate20.npz
│ └── t_his25_1_thre0.500_t_pred100_thre0.100_filtered_dlow.npz，但是我看见训练的代码里指定了cfg参数以后，它对应的cfg/yml文件里就有指定这两个文件的具体地址需要调用，请问应该怎么修改呢，还有疑问就是在哪里指明了调用数据集三维姿态的.npz文件呢，非常感谢

**Comment by LinghaoChan** [comment]
这是在训练过程中监控指标的，你直接把用到报错的地方的计算屏蔽即可。

**Comment by xiaomadegit** [comment]
好的感谢，我尝试一下
