### ISSUE TITLE
Why using zero_module() on some linear layer?

### ISSUE THREAD

**Issue by daidaiershidi** [LinghaoChan/HumanMAC#2]
Thank you for your inspiring work. I am curious as to why there are some linear layers that have parameters set to 0 at initialization, which is not discussed in the paper. Is there any benefit to this and which layers are best set to 0?

**Comment by daidaiershidi** [comment]
And what is the input of self-attention in Figure 7?

**Comment by LinghaoChan** [comment]
> Thank you for your inspiring work. I am curious as to why there are some linear layers that have parameters set to 0 at initialization, which is not discussed in the paper. Is there any benefit to this and which layers are best set to 0?

Thank you for your interest. Note that our work does not benefit from the network design, which is a simple architecture. Our HumanMAC model mainly benefits from the mask-completion mechanism. For the ``zero_module()`` setting, we extend it from [another repo](https://github.com/mingyuan-zhang/MotionDiffuse/blob/aba848edd22133919ca96b67f4908399c67685b1/text2motion/models/transformer.py#L51). Please refer to it. I am performing the ablation study on the ``zero_module()`` setting. There are three ``zero_module()`` references in the ``./model/transformer.py``. The ablation includes all $2^3=8$ combinations of w/ or w/o the ``zero_module()`` setting. I have not observed a significant difference with the official implementation on quantitative and visualized results.

**Comment by LinghaoChan** [comment]
> And what is the input of self-attention in Figure 7?

The output of the last layer. Please refer to the [code](https://github.com/LinghaoChan/HumanMAC/blob/1c7b183e79fdc3eb8dc49dafc0badd0c52216018/models/transformer.py#L268).
