### ISSUE TITLE
Mutimodal data

### ISSUE THREAD

**Issue by SugarMuzi** [LinghaoChan/HumanMAC#3]
Hi!researcher,your work is very amazing. I downloaded your code to try to do human motion prediction task,and now
 i have a question：

- I noticed that i should download some datasets which include data_3d_h36m.npz, data_3d_h36m and so on.but why i also should download data_mutil_modal? What modal of data does the data_mutil_modal contain?

**Comment by LinghaoChan** [comment]
Hi, Thank you for your interest! 

The `data_mutil_modal` is used for calculating `multi-modal` metrics, *e.g.* `MMADE`, and `MMFDE`. 

The HMP task is not a multi-modality task. The names of `MMADE` and `MMFDE` are extended from the DLow[1] baseline. The data file is convenient for you to calculate `multi-modal` metrics. You can download the data from the Google Drive link provided in the `README`. 

I quote the description of `multi-modal` metrics from [1]: 

> Multi-Modal ADE (MMADE): the multi-modal version of ADE that obtains multi-modal ground truth future motions by grouping similar past motions. 
> Multi-Modal FDE (MMFDE): the multi-modal version of FDE.

[1]: Yuan, Y., & Kitani, K. (2020). Dlow: Diversifying latent flows for diverse human motion prediction. In Computer Vision–ECCV 2020: 16th European Conference, Glasgow, UK, August 23–28, 2020, Proceedings, Part IX 16 (pp. 346-364). Springer International Publishing.

**Comment by SugarMuzi** [comment]
Thanks for  your replay, i got it.
