### ISSUE TITLE
Condition in diffusion

### ISSUE THREAD

**Issue by Haodong-Yan** [LinghaoChan/HumanMAC#5]
Hi,
I am very interested in your work. And there is one question for me. The noise prediction network takes two arguments (y_t and t) in the paper. But in the repo, there is a condition (traj_dct_mod) which also input into the noise prediction network. what is the meaning of this condition and why add it?

**Comment by LinghaoChan** [comment]
Hi~, @yhd-ai. Thanks for your attention. For the meaning of `traj_dct_mod`, please refer to Appendix A in the paper. It can be obtained by y. The modulation mechanism is also introduced in the noise prediction network of MotionDiffuse [1].

> To obtain temporal relationships, the FiLM module is modulated by the first K-frame modulating motion’s DCT spectrum and the diffusion time embedding. 

[1]: Zhang, Mingyuan, et al. "Motiondiffuse: Text-driven human motion generation with diffusion model." arXiv preprint arXiv:2208.15001 (2022).

**Comment by Haodong-Yan** [comment]
Thanks for your patient guidance~ sorry for disturbing you due to my careless reading
