### ISSUE TITLE
To Reproduce the Results

### ISSUE THREAD

**Issue by lzhyu** [LinghaoChan/HumanMAC#6]
Hi, your work's awesome. I'm trying to reproduce the results on paper. I followed the command you provided in README for training and evaluation. However, the numbers I got were (APD:0.673, ADE: 0.212, FDE: 0.261, MMADE: 0.426, MMFDE: 0.469), which is different from those on the paper. Do you think that's due to some difference between the configuration or hyperparameters or is that just because of randomness in training? How can I reproduce results close to those on the paper?
Your help will be highly appreciated!

**Comment by LinghaoChan** [comment]
@lzhyu , thanks for your attention. Which dataset do you use? HumanEva-I?

**Comment by lzhyu** [comment]
Yes. For Human3.6M, the results are reasonable.

**Comment by LinghaoChan** [comment]
Please set the `mod_test: 1.0` to `mod_test: 0.5` in `./cfg/humaneva.yml` and have a try. This is the modulation ratio. Details have been discussed at issue https://github.com/LinghaoChan/HumanMAC/issues/5.

**Comment by lzhyu** [comment]
Hi,
By setting mod_test to 0.5 and mod_train to 0.8, I got numbers close to those in the paper.
Thanks a lot for your help!

**Comment by LinghaoChan** [comment]
Thanks for your issue. I have revised the default parameter setting.
