### ISSUE TITLE
Reproduce problem of HumanEva-I

### ISSUE THREAD

**Issue by damNull** [LinghaoChan/HumanMAC#7]
We follow the experiment setting in the article. However, we cannot reproduce the result of HumanEva-l. The hyper-parameters we use are
```
dataset: 'humaneva'
t_his: 15
t_pred: 60
batch_size: 64
num_epoch: 501
num_data_sample: 50000
num_val_data_sample: 5000
lr: 3.e-4
n_pre: 10
multimodal_path: ./data/humaneva_multi_modal/t_his15_1_thre0.500_t_pred60_thre0.010_index_filterd.npz
data_candi_path: ./data/humaneva_multi_modal/data_candi_t_his15_t_pred60_skiprate15.npz
padding: 'LastFrame'
Complete: True
noise_steps: 1000
ddim_timesteps: 100
scheduler: 'Cosine' # 'Cosine' 'Linear' 'Sqrt' 'Sigmoid'
num_layers: 4
num_heads: 8
latent_dims: 512
dropout: 0.2
mod_train: 1.
mod_test: 0.5
dct_norm_enable: False
```
The code running environment is PyTorch 2.0.0 with CUDA 11.7 and RTX 3090. 
Could you please help me to resolve this problem? In addition, the result of Human3.6M can be reproduced perfectly. 😁😁

**Comment by LinghaoChan** [comment]
Thanks for your attention. Maybe you can refer to the issue https://github.com/LinghaoChan/HumanMAC/issues/6 first. 

Can it resolve your concern?

**Comment by damNull** [comment]
Thanks a lot for your help!
