### ISSUE TITLE
About the re-targeting code from AMASS to Human3.6M format

### ISSUE THREAD

**Issue by knightleyaa** [LinghaoChan/HumanMAC#8]
Hi！ I would like to know whether you have a plan to release the re-targeting code from AMASS to the Human3.6M format.
Thanks!

**Comment by LinghaoChan** [comment]
Thanks for your question. I will update the corresponding module. 🤝

**Comment by LinghaoChan** [comment]
In commit 20b0b948fb34f85720a62cc12d8d6aee14711ebe, we provide the codes for retargeting. 

🚩 Please check the update in [retargeting code](https://github.com/LinghaoChan/HumanMAC/tree/main/motion-retargeting).

**Comment by LinghaoChan** [comment]
It seems that the issue has been resolved. I will close it.
