### ISSUE TITLE
A question about the data

### ISSUE THREAD

**Issue by pawpaw1243** [LinghaoChan/HumanMAC#9]
Hi ,after reading the paper, I have gained a lot. and admire your experiment very much, but I have encountered some troubles when trying to implement the algorithm. here is a request about the code about the file (data_candi_t_his25_t_pred100_skiprate20.npz ) in the data. If possible, could you share the code that generated this file? Or how to generate such file?

**Comment by LinghaoChan** [comment]
Hi @pawpaw1243 

Thanks for your comment. Could you please provide the detailed relative path of the file?

**Comment by LinghaoChan** [comment]
@pawpaw1243 Has this issue been resolved? The data usage is extended from the DLow and GSPS. Maybe you can refer to these projects.

**Comment by LinghaoChan** [comment]
Close it. If any problem, reopen it or raise another.
